services:
  - type: web
    name: spms
    runtime: node
    repo: https://github.com/sam1136pp/student-project-management-system
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: spms_render_production_secret_2026
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
